### ISSUE TITLE
upload files.

### ISSUE THREAD

**Issue by INNFINITEMINDS** [darshanmandge/SimulatorExamples#1]
Respected Sir,
please upload SimulatorExamples so that we can take it as reference.
thank you,
arpit

**Comment by darshanmandge** [comment]
Hi Arpit,

If you are interested in **NEURON** simulator based code examples, you could find them here:
https://neuron.yale.edu/neuron/docs

It has plenty of exercises based on NEURON, Python with NEURON with codes for most of them. You could explore this page.

Some other really good resources are:
1. **Set of 5 Tutorials by Andrew Gillies and David Sterratt**: http://web.mit.edu/neuron_v7.4/nrntuthtml/index.html

2. **NEURON + Python Tutorial**: https://neuron.yale.edu/neuron/static/docs/neuronpython/index.html

3. **NEURON Hands-on Course 2008 material** (Though a bit old but still relevant): https://neuron.yale.edu/neuron/static/courses/2008/course/handson.html

4. Some other **tutorials**: http://www.kem.org/neuron/tutorial.html

5. If you want to find published models based on NEURON, MATLAB, Python and other simulators you could look up **ModelDB**: https://senselab.med.yale.edu/ModelDB/FindByRegionList.cshtml

Best Wishes,
Darshan

**Comment by INNFINITEMINDS** [comment]
TAHNK YOU SIR, FOR A THIS.
RESPECTED SIR,
CAN U PLEASE HELP HOW CAN I PLOT steady state parameter and time constant 
like that of Hh.Also sir how did u plot this graphs in the paper u have published on modeldb (the paper of DRG neuron) .
I want to plot the graphs.
Hope u will help.
Awaiting for your response.
Thank you,
Peace

**Comment by darshanmandge** [comment]
Your question is answered here:
https://www.neuron.yale.edu/phpBB/viewtopic.php?f=28&t=1156
**Using the Grapher to plot voltage-dependent gating variables**
