### ISSUE TITLE
Required Your Guidance if possible....

### ISSUE THREAD

**Issue by INNFINITEMINDS** [darshanmandge/SimulatorExamples#2]
Respected sir,
i want to plot this type of results .i have attached the figure below. How can I do this with NEURON?
IF U KNOW HOW TO DO THAT, THAN PLEASE SHARE...JUST SHOW THE WAY ..(Give some directions soi could go further)
------------------------link-------------------------------------------
===============================================================
https://neuronaldynamics.epfl.ch/online/Ch3.S1.html
============================================================
--------------want to plot using NEURON----------------------------------------
![image](https://user-images.githubusercontent.com/28722237/54108689-e0acf780-4399-11e9-9555-fc53f65a56ea.png)
-------------------------------------------------------------------------------------------------
# question 2,.
> how can i do this type of model .If u have any refrence model than please share .
![Untitled](https://user-images.githubusercontent.com/28722237/54109059-d17a7980-439a-11e9-8533-692637ef5ba9.png)

Thank you
Awaiting for your Response.
Peace :)

**Comment by darshanmandge** [comment]
Hi,

The synaptic currents in the figure can be seen as combination of 2 phases: an **exponential rising phase** starting from zero to highest peak, and an **exponential falling phase** from the peak to base. So, you can code them as 2 exponential terms which I guess is also explained in the text of your course link. Sometimes special mathematical functions such as Alpha function can give your the desired shape.

NEURON has some inbuilt mechanisms such as Alphasyapse, expSyn and exp2Syn to help you here. Read about them from documentation or NEURON book. You don't need to make them from scratch. This will help you get started with some simple synaptic current simulations. Find the rising and falling time constants for each current, make an instance of any of the above mechanisms for each synapse and assign the time constant values.

You can also find their mod files in your NEURON installation folder if you want to learn more about them. 

Best Wishes,
Darshan
PS - If you decide to experiment with original mod file, don't change the original mod file in the setup folder. Instead make a copy in a local folder and then do your changes. You will only need them if you want to create your own specialized mechanisms. They can act as a template for creating complex synapses e.g. a NMDA synapse with Mg2+ dependency.

**Comment by INNFINITEMINDS** [comment]
Thank you very much  sir.
I will follow the way u had showed.Once again thank you sir .
peace :)
